language: python
before_install:
- curl -sSf https://gitlinks.github.io/cl-bins/install.sh | sh
install:
- pip install tox
script:
- tox
- "~/.gitlinks/hermes-ci-rust"
env:
  matrix:
  - TOXENV=py27
  - TOXENV=py34
